# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013, Google Inc.
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y += context.o cryptlib.o ex_data.o mem.o mem_clr.o
obj-y += o_str.o packet.o
obj-y += bn/
obj-y += ec/
obj-y += stack/

