# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013, Google Inc.
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y += ec_asn1.o ec_curve.o ec_key.o ec_kmeth.o ec_lib.o
obj-y += ec_mult.o ecdsa_ossl.o ecdsa_vrf.o ecp_nist.o
obj-y += ecp_nistp256.o ecp_nistputil.o ecp_smpl.o

