# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013, Google Inc.
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-y += bn_add.o bn_asm.o bn_ctx.o bn_div.o bn_exp.o
obj-y += bn_gcd.o bn_intern.o bn_lib.o bn_mod.o bn_mont.o
obj-y += bn_mul.o bn_nist.o bn_shift.o bn_sqr.o bn_word.o
